name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting-test:
    name: Run linting test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git-repository
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint and Prettier
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
